name: Check Python Data Analyst Jobs

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 00:00（北京 08:00）运行

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ✅ 允许发布到 Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Upgrade pip & install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job checker
        run: python check_jobs.py

      # 生成一个简单网页用于展示和下载结果
      - name: Prepare site
        run: |
          mkdir -p site
          cp -f remote_companies_with_python_jobs_cached.xlsx site/ || true
          cp -f companies.xlsx site/ || true
          echo '<h1>Data Analyst Jobs Results</h1><ul>' > site/index.html
          [ -f site/companies.xlsx ] && echo '<li><a href="companies.xlsx">Download companies.xlsx</a></li>' >> site/index.html
          [ -f site/remote_companies_with_python_jobs_cached.xlsx ] && echo '<li><a href="remote_companies_with_python_jobs_cached.xlsx">Download job results</a></li>' >> site/index.html
          echo '</ul><p>Generated at $(date -u)</p>' >> site/index.html

      # 发布到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
