name: Check Python Data Analyst Jobs

on:
  pull_request:           # PR 提交/更新自动跑
  workflow_dispatch:      # 手动触发
  schedule:
    - cron: "0 0 * * *"   # 每天 UTC 00:00 运行（北京是 08:00）

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"                # ✅ Pip 依赖缓存

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job checker
        run: |
          python check_jobs.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: python_jobs_results
          path: remote_companies_with_python_jobs_cached.xlsx
          if-no-files-found: ignore   # ✅ 文件不存在不报错

      - name: Upload cache
        uses: actions/upload-artifact@v4
        with:
          name: job_cache
          path: cache.json
          if-no-files-found: ignore   # ✅ 文件不存在不报错
